services:
  app:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    command: "bash"
    tty: true
    stdin_open: true
    environment:
      - PORT=3000
    ports:
      - 3000:3000

